### ISSUE TITLE
forwarder doesn't close outbound connections in some cases.

### ISSUE THREAD

**Issue by fffw** [getlantern/http-proxy#59] opened 2015-11-16 08:51 UTC
Seem from the vultr server [fp-jp-20151114-006](https://my.vultr.com/subs/?SUBID=2887995#graphs).

`http-proxy` process has a few ESTABLISHED connections to 80 port of different target servers, but there's no inbound connection to proxy listen port.

**Comment by uaalto** [comment] 2015-11-16 10:54
I'm suspicious of this:
https://github.com/getlantern/http-proxy/blob/master/forward/forward.go#L88

How can the conn become nil if previously checked for an error condition?

**Comment by fffw** [comment] 2015-11-16 12:18
Oh I guess `timeoutTransport.Dial` in https://github.com/getlantern/http-proxy/blob/master/forward/forward.go#L57 will always be nil because `dialerFunc` is assigned afterwards!

**Comment by uaalto** [comment] 2015-11-16 12:31
That would make the idleconnection not act, and we are not testing that case actually. We are only testing client<->proxy, not proxy<->server.
We should try setting this in proper order and adding a test case for this. This could explain idle connection buildup.

**Comment by uaalto** [comment] 2015-11-16 12:38
We should be getting "too many files open" errors though...

**Comment by uaalto** [comment] 2015-11-16 18:17
Connections weren't indeed being closed by means of idleconnection. The latest commits fix it, and add tests, also for the CONNECT case, for outbound origin connections.

**Comment by myleshorton** [comment] 2015-11-16 18:25
Awesome @uaalto. The other part that ideally would happen here is that when the client closes the connection, we also always close the connection to the destination server and vice-versa.

**Comment by uaalto** [comment] 2015-11-16 18:44
I'll add that as an issue, to conduct a proper investigation.

**Comment by uaalto** [comment] 2015-11-17 10:15
I think we should be closing all the connections now, what do you think @fffw?
The server problems might not be caused by this, but with the new tools we can spot the cause with more information.

**Comment by fffw** [comment] 2015-11-17 10:19
Yeah I also think so.

**Comment by uaalto** [comment] 2015-11-17 10:20
ok!

**Closed by uaalto** 2015-11-17 10:20 UTC

**Comment by myleshorton** [comment] 2015-11-17 18:50
I agree idletiming should be closing connections correctly now, but to me that should also be a last resort @uaalto and @fffw -- i.e. we should be closing connections whenever it's obvious we should, such as when clients disappear. We probably already close them in cases like the server or client sending `Connection: close`, but it would be worth checking to make sure.

**Comment by uaalto** [comment] 2015-11-17 18:53
Yes, I agree. I had opened another issue to handle the general case, just to keep them identified: https://github.com/getlantern/http-proxy/issues/63

**Comment by myleshorton** [comment] 2015-11-17 18:56
Perfect @uaalto thanks!
